### ISSUE TITLE
Unable to convert Dynamo storage representation to a Tomcat Session with any converter provided

### ISSUE THREAD

**Issue by asundaram** [aws/aws-dynamodb-session-tomcat#24]
Hi,

Followed all the instructions to configure DynamoDB session for Tomcat 7.0.57 ( JDK version - 1.6.0_38) and running into below exception. 

SEVERE: Error processing request
com.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.converters.SessionConversionException: Unable to convert Dynamo storage representation to a Tomcat Session with any converter provided
	at com.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.converters.TomcatSessionConverterChain.toSession(TomcatSessionConverterChain.java:41)
	at com.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.converters.SessionConverter.toSession(SessionConverter.java:42)
	at com.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.DynamoSessionStorage.loadSession(DynamoSessionStorage.java:47)
	at com.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.DynamoDBSessionStore.load(DynamoDBSessionStore.java:84)
	at org.apache.catalina.session.PersistentManagerBase.swapIn(PersistentManagerBase.java:747)
	at org.apache.catalina.session.PersistentManagerBase.findSession(PersistentManagerBase.java:511)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:2913)
	at org.apache.catalina.connector.Request.getSession(Request.java:2310)
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:897)
	at com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:41)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:662)

I also see logs with the following warning message -

Apr 24, 2015 5:54:05 PM com.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.DynamoDBSessionStore load
WARNING: Unable to load session with id E702B419E931BBCA13B4BD2ECDEDF6B3

**Comment by shorea** [comment]
@asundaram Is this a fresh install of the session manager? Which version are you using?

**Comment by asundaram** [comment]
Yes, this is a fresh install. Version of session manager is 2.0.0

**Comment by Selindek** [comment]
Just an idea:
I got a similar exception when I run the server locally and accidentally started an other wepapp too (under the same tomcat), and the sessionmanager took effect for this other app too and tried to load a session for the second app what was stored by the first one.

**Comment by shorea** [comment]
@Selindek interesting observation. I can see that being a problem especially when custom objects are stored in the session that may not be found in the classloader of another webapp. That particular use case can be accommodated by having a separate table for each webapp using the configuration options as shown in http://docs.aws.amazon.com/AWSSdkDocsJava/latest//DeveloperGuide/java-dg-tomcat-session-manager.html.

@asundaram Did you create the table manually or did the SessionManager create it automatically?

**Comment by asundaram** [comment]
No there is no other web app on this Tomcat instance at this point. The App uses Spring Framework to handle most of the session stuff, wondering if this is a cause. Does the Tomcat session manager support Spring? Also I see another weird thing - the value in the JSESSIONID cookie and what gets written in catalina.out in the messages (com.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.DynamoDBSessionStore load
WARNING: Unable to load session with id E702B419E931BBCA13B4BD2ECDEDF6B3) are totally different. Not sure what's causing this or if this is expected?

@shorea I created the table manually. I have also tried the SessionManager create it, but all leads to the same issue.

**Comment by shorea** [comment]
My gut instinct is that it's a classloader issue. When we serialize and deserialize the session we need the class loader of the current context to properly handle custom objects that may be present in session data. I'm trying to get together a debug jar with better logging that will hopefully shed more light on this issue. Unfortunately the way we are handling compatibility from 1.x versions we are swallowing the actual exception and throwing a generic exception in https://github.com/aws/aws-dynamodb-session-tomcat/blob/master/src/main/java/com/amazonaws/services/dynamodb/sessionmanager/converters/TomcatSessionConverterChain.java.

**Comment by asundaram** [comment]
Ok thanks, will wait for the debug jar.

**Comment by asundaram** [comment]
I reverted to use 1.0.5 version of the Tomcat Session Manager and started to see the actual unsuppressed exception. It turns out that one of the objects that we were trying to store was not Serializable. We made the change and started seeing the session data being written properly to the DynamoDB table. After this I upgraded back to 2.0.0 version and saw the createdAt and lastUpdatedAt timestamps on the table item set to 0. Tracing back in code, getter and setter for createdTime and lastUpdatedTime are deprecated. I don't see it being set any other way, am I missing something or is this a bug?

**Comment by shorea** [comment]
Ahh I see. I apologize this was so difficult to debug, we definitely need to improve the logging so those exceptions are not suppressed. 

createdTime and lastUpdatedTime are no longer used in version 2.0. All session data is stored in the sessionData attribute. Until we completely remove createdTime and lastUpdatedTime from the model class they will continue to show up in the table, this is to be expected.

**Comment by shorea** [comment]
Updated release 1.0.5 and 2.0.0 with improved logging. Thanks @asundaram for bringing this to our attention!
