### ISSUE TITLE
the current release(2.0.1) doesn't work with ap-northeast-2 region.

### ISSUE THREAD

**Issue by dary4n** [aws/aws-dynamodb-session-tomcat#37]
the current release was built with aws-java-sdk ver 1.10.20 (from pom.xml), so doesn't support ap-northeast-2 region. an update to the aws-java-sdk is required ver 1.10.45 or newer for supporing ap-northeast-2 region.

**Here's the catalina.out**

org.apache.catalina.LifecycleException: Failed to initialize component [com.amazonaws.services.dynamodb.sessionmanager.DynamoDBSessionManager[/manager]]
           at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:106)
           at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:139)
           at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5443)
           at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
           at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
           at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
           at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
           at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1113)
           at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1671)
           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
           at java.util.concurrent.FutureTask.run(FutureTask.java:262)
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
           at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: No region provided
           at com.amazonaws.tomcatsessionmanager.amazonaws.AmazonWebServiceClient.setRegion(AmazonWebServiceClient.java:351)
           at com.amazonaws.services.dynamodb.sessionmanager.DynamoDBSessionManager.createDynamoClient(DynamoDBSessionManager.java:151)
           at com.amazonaws.services.dynamodb.sessionmanager.DynamoDBSessionManager.initInternal(DynamoDBSessionManager.java:139)
           at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
           ... 13 more

**Comment by shorea** [comment]
I've updated the dependency on the SDK and released it under 2.0.2. It should appear in Maven Central in a couple of hours.

**Comment by shorea** [comment]
Verified new version is in Maven Central
