### ISSUE TITLE
DefaultDynamoSessionItemConverter.toSessionItem() throws error on line 35

### ISSUE THREAD

**Issue by whennemuth** [aws/aws-dynamodb-session-tomcat#54]
We have 2 elastic load balanced EC2 instances each running a tomcat 7 java application in a docker container.
The session manager seems to be able to save session state out to dynamodb as I see an new item appear in the Tomcat_SessionState table when I begin to navigate around the website. However, at the same time, tailing the catalina log shows exceptions you'd expect to see if the java objects that are being stored as session attributes did not implement the serializable interface.
However they do (UserSession.java).
Also, if I restart tomcat, and then resume at the browser with the same page open (and ostensibly the same sessionId from lingering cookie), I'd expect to see an attempt to deserialize the existing Tomcat_SessionState table item, but it creates a new item as if a new session were now in effect.

Does the session handler write out partial entries, leaving out those attributes that fail serialization?
If so, does the session handler regard that entry as corrupted and start new sessions regardless of same sessionId in http request?
How do I get at the root cause of this?

I am using 2.01 as 2.04 dropped support for tomcat 7

Below is a relevant excerpt from the catalina log:

2017-03-31 16:24:20,919 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] WARN  com.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.DynamoDBSessionStore- Unable to load session with id 0DBDA0968BA1802689AD8E90CB488629
2017-03-31 16:25:20,923 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] WARN  org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/kc]- Cannot serialize session attribute UserSession for session 0DBDA0968BA1802689AD8E90CB488629
java.io.NotSerializableException: java.lang.Object
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at java.util.concurrent.ConcurrentHashMap.writeObject(ConcurrentHashMap.java:1413)
        at sun.reflect.GeneratedMethodAccessor712.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at org.apache.catalina.session.StandardSession.writeObject(StandardSession.java:1695)
        at org.apache.catalina.session.StandardSession.writeObjectData(StandardSession.java:1101)
        at com.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.converters.DefaultDynamoSessionItemConverter.toSessionItem(DefaultDynamoSessionItemConverter.java:35)
        at com.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.converters.SessionConverter.toSessionItem(SessionConverter.java:37)
        at com.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.DynamoSessionStorage.saveSession(DynamoSessionStorage.java:58)
        at com.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.DynamoDBSessionStore.save(DynamoDBSessionStore.java:99)
        at org.apache.catalina.session.PersistentManagerBase.writeSession(PersistentManagerBase.java:832)
        at org.apache.catalina.session.PersistentManagerBase.processMaxIdleBackups(PersistentManagerBase.java:1038)
        at org.apache.catalina.session.PersistentManagerBase.processPersistenceChecks(PersistentManagerBase.java:462)
        at org.apache.catalina.session.PersistentManagerBase.processExpires(PersistentManagerBase.java:441)
        at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:517)
        at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1352)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1530)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1519)
        at java.lang.Thread.run(Thread.java:745)

**Comment by whennemuth** [comment]
BTW, I am using 2.01 as 2.04 dropped support for tomcat 7

**Comment by whennemuth** [comment]
Child objects of serializable class are not serializable.
Can replicate the same issue with the standard tomcat session manager.
